config/routes.rb
Rails.application.routes.draw do
  resources :availabilities
  resources :listings
  resources :hosts
  resources :updaters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'hosts#index'

  resources :hosts do
    resources :listings
  end

  post 'updater',
       to: 'updaters#refresh_data',
       as: :refresh_scraped_data
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :host
  has_many :availabilities, dependent: :destroy

  def booked_days
    booked_array = []
    temp_booked = availabilities.select{|a| a.available == false}
    if temp_booked.any?
      temp_booked.each_with_index do |day, index|
        booked_array << {title: "Event ${index}",
                         start: day.availability_date,
                         end: day.availability_date + 1.day,
                         repeat: 'never',
                         categoryId: 2}
      end
    end
    booked_array
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  # def new
  #   @listing = Listing.new
  # end

  # GET /listings/1/edit
  # def edit
  # end
  #
  # # POST /listings or /listings.json
  # def create
  #   @listing = Listing.new(listing_params)
  #
  #   respond_to do |format|
  #     if @listing.save
  #       format.html { redirect_to @listing, notice: "Listing was successfully created." }
  #       format.json { render :show, status: :created, location: @listing }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @listing.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /listings/1 or /listings/1.json
  # def update
  #   respond_to do |format|
  #     if @listing.update(listing_params)
  #       format.html { redirect_to @listing, notice: "Listing was successfully updated." }
  #       format.json { render :show, status: :ok, location: @listing }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @listing.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /listings/1 or /listings/1.json
  # def destroy
  #   @listing.destroy
  #   respond_to do |format|
  #     format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:host_id, :airbnb_id, :address1, :address2, :city, :state, :postal_code, :active, :last_scraped)
    end
end

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<% if @listings.any? %>
  <% @listings.sort_by { |l| l.airbnb_id }.each do |listing| %>
    <listing :listing="<%= listing.to_json %>"></listing>
  <% end %>
<% end %>

<br>

<%= link_to 'All Hosts', hosts_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Availability</h1>
<p>
  <strong>Host:</strong>
  <%= @listing.host.host_name %>
</p>

<p>
  <strong>Listing Airbnb ID:</strong>
  <%= @listing.airbnb_id %>
</p>

<p>
  <strong>Last scraped:</strong>
  <%= @listing.last_scraped %>
</p>

<availability_calendar :events="<%= @listing.booked_days.to_json %>"></availability_calendar>

<%= link_to 'Back', host_path(@listing.host_id) %>|
<%= link_to 'All Hosts', hosts_path %>