config/routes.rb
Rails.application.routes.draw do
  resources :availabilities
  resources :listings
  resources :hosts
  resources :updaters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'hosts#index'

  resources :hosts do
    resources :listings
  end

  post 'updater',
       to: 'updaters#refresh_data',
       as: :refresh_scraped_data
end

app/models/host.rb
class Host < ApplicationRecord
  has_many :listings, dependent: :destroy

  after_create :initial_scrape


  def refresh_host
    scraping_agent = ScrapingClient.new
    #TODO I'd like to wrap to throw this to a queue and wrap their processing in a transaction
    self.update(last_scraped: Time.now)
    delete_listings
    host_listings(scraping_agent).each do |airbnb_listing|
      available_months = scraping_agent.listing_availability(airbnb_listing['id'])
      if available_months.any?
        airbnb_listing = Listing.create(host_id: self.id,
                                        airbnb_id: airbnb_listing['id'],
                                        last_scraped: Time.now)
        process_availabilities(available_months, airbnb_listing)
      end
    end
  end

  private

  def host_listings(scraping_agent)
    all_listings = []
    counter = 0
    loop do
      listing_batch = scraping_agent.fetch_listings(self.airbnb_id, page: counter)
      all_listings += listing_batch
      break if listing_batch.length < 10 or all_listings.length >= 20
      counter += 1
    end
    all_listings
  end

  def process_availabilities(availability_months, listing)
    counter = 0
    availability_months.each do |availability_month|
      current_avails = availability_month['days']
      current_avails.try(:each) do |a|
        avail_data = a['calendarDate'].to_date
        if avail_data >= Date.today
          counter += 1
          Availability.create(listing_id: listing.id,
                              availability_date: a['calendarDate'].to_date,
                              available: a['available'])
          return true if counter >= 60
        end
      end

    end
  end

  def delete_listings
    listings.map { |listing| listing.destroy } unless listings.nil?
  end


  def initial_scrape
    ScrapeHostJob.perform_later(self)
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: %i[ show edit update destroy ]

  # GET /hosts or /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1 or /hosts/1.json
  def show
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts or /hosts.json
  def create
    @host = Host.new(host_params)

    respond_to do |format|
      if @host.save
        format.html { redirect_to @host, notice: "Host was successfully created." }
        format.json { render :show, status: :created, location: @host }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hosts/1 or /hosts/1.json
  def update
    respond_to do |format|
      if @host.update(host_params)
        format.html { redirect_to @host, notice: "Host was successfully updated." }
        format.json { render :show, status: :ok, location: @host }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @host.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hosts/1 or /hosts/1.json
  def destroy
    @host.destroy
    respond_to do |format|
      format.html { redirect_to hosts_url, notice: "Host was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def host_params
      params.require(:host).permit(:host_name, :airbnb_id, :active, :last_scraped)
    end
end

app/views/hosts/_form.html.erb
<%= form_with(model: host, local: true) do |form| %>
  <% if host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
        <% host.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :host_name %>
    <%= form.text_field :host_name %>
  </div>

  <div class="field">
    <%= form.label :airbnb_id %>
    <%= form.number_field :airbnb_id %>
  </div>

  <div class="field">
    <%= form.label :last_scrapped %>
    <%= form.datetime_select :last_scraped %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hosts/edit.html.erb
<h1>Editing Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Delete', @host, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', @host %> |
<%= link_to 'All Hosts', hosts_path %>

app/views/hosts/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Refresh settings', updaters_path %>

<h1>Hosts</h1>

<% @hosts.each do |host| %>
  <host :host="<%= host.to_json %>"></host>
<% end %>

<br>

<%= link_to 'New Host', new_host_path %>

app/views/hosts/new.html.erb
<h1>New Host</h1>

<%= render 'form', host: @host %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<p id="notice"><%= notice %></p>
<% if Rails.env.production? %>
  <% listing_api_path = "https://rabbu5.herokuapp.com/updaters/#{@host.id}" %>
<% else %>
  <% listing_api_path = "http://localhost:3000/updaters/#{@host.id}" %>
<% end %>
<%= hidden_field_tag :vue_api_path, listing_api_path %>

<p>
  <strong>Host name:</strong>
  <%= @host.host_name %>
</p>

<p>
  <strong>Airbnb:</strong>
  <%= @host.airbnb_id %>
</p>

<p>
  <strong>Last scrapped:</strong>
  <%= @host.last_scraped %>
</p>

Listings: <%= @host.listings.try(:length) %> [Limited to 20 Max]
<hr>

<% if @host.listings.any? %>
  <% @host.listings.sort_by { |l| l.airbnb_id }.each do |listing| %>
    <listing :listing="<%= listing.to_json %>"></listing>
  <% end %>
<% end %>
<hr>

<%= link_to 'Edit', edit_host_path(@host) %> |
<%= link_to 'All Hosts', hosts_path %>