config/routes.rb
Rails.application.routes.draw do
  resources :availabilities
  resources :listings
  resources :hosts
  resources :updaters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'hosts#index'

  resources :hosts do
    resources :listings
  end

  post 'updater',
       to: 'updaters#refresh_data',
       as: :refresh_scraped_data
end

app/models/updater.rb
class Updater < ApplicationRecord
end

app/controllers/updaters_controller.rb
class UpdatersController < ApplicationController
  before_action :set_updater, only: %i[ edit update destroy ]

  # GET /updaters or /updaters.json
  def index
    # @listings = Listing.all.order(airbnb_id: :asc)
    # respond_to do |format|
    #   format.json { render json: @listings}
    # end
  end

  # GET /updaters/1 or /updaters/1.json
  def show
    @listings = Listing.where(host_id: params[:id]).order(airbnb_id: :asc)
    respond_to do |format|
      format.json { render json: @listings}
    end
  end

  # GET /updaters/new
  def new
    @updater = Updater.new
  end

  # GET /updaters/1/edit
  def edit
  end

  # POST /updaters or /updaters.json
  def create
    @updater = Updater.new(updater_params)

    respond_to do |format|
      if @updater.save
        format.html { redirect_to @updater, notice: "Updater was successfully created." }
        format.json { render :show, status: :created, location: @updater }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @updater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updaters/1 or /updaters/1.json
  def refresh_data
    RefreshDataJob.perform_later()
    redirect_to hosts_path, notice: "Data refresh has been scheduled."
  end
  #
  # # DELETE /updaters/1 or /updaters/1.json
  # def destroy
  #   @updater.destroy
  #   respond_to do |format|
  #     format.html { redirect_to updaters_url, notice: "Updater was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_updater
      @updater = Updater.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def updater_params
      params.fetch(:updater, {})
    end
end

app/views/updaters/_form.html.erb
<%= form_with(model: updater, local: true) do |form| %>
  <% if updater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(updater.errors.count, "error") %> prohibited this updater from being saved:</h2>

      <ul>
      <% updater.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/updaters/edit.html.erb
<h1>Editing Updater</h1>

<%= render 'form', updater: @updater %>

<%= link_to 'Show', @updater %> |
<%= link_to 'Back', updaters_path %>

app/views/updaters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Updater</h1>

<%= button_to 'Schedule Recurring Data Refresh', refresh_scraped_data_path, method: :post %>

<br>

<%= link_to 'All Hosts', hosts_path %>

app/views/updaters/new.html.erb
<h1>New Updater</h1>

<%= render 'form', updater: @updater %>

<%= link_to 'Back', updaters_path %>

app/views/updaters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_updater_path(@updater) %> |
<%= link_to 'Back', updaters_path %>